

{{- range .Values.users }}
---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "koodirectory.labels" $ | nindent 4 }}
spec:
{{- with .commonName }}
  commonName: {{ . }}
{{- end }}
{{- with .passwordHash }}
  passwordHash: {{ . }}
{{- end }}
{{- with .disabled}}
  disabled: {{ . }}
{{- end }}
{{- with .email }}
  email: {{ . }}
{{- end }}
{{- with .comment}}
  comment: {{ . }}
{{- end }}
{{- with .uid}}
  uid: {{ . }}
{{- end }}
{{- end }}
