

{{- range .Values.users }}
---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "koodirectory.labels" $ | nindent 4 }}
spec:
{{- with .commonNames }}
  commonNames:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .passwordHash }}
  passwordHash: {{ . }}
{{- end }}
{{- with .disabled}}
  disabled: {{ . }}
{{- end }}
{{- with .emails }}
  emails:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .comment}}
  comment: {{ . }}
{{- end }}
{{- with .uid}}
  uid: {{ . }}
{{- end }}
{{- end }}
