---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: user-sample
spec: {}
# Add fields here
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: group-sample
spec: {}
# Add fields here
---
apiVersion: directory.koobind.io/v1alpha1
kind: Binding
metadata:
  name: binding-sample
spec: {}
# Add fields here
