---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: lhamilton
  namespace: koo-system
spec:
  commonName: Lewis HAMILTONX
  passwordHash: $2a$10$0XqNZP13.lTc6eh1tidUEu6pFkJ8tRmz5qdMNuTah7AdH7uQQwpIO  # hamiltonl
  email: lewis@mercedes.com
  uid: 44
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: lh-mclaren
  namespace: koo-system
spec:
  user: lhamilton
  group: mclaren
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: lh-mercedes
  namespace: koo-system
spec:
  user: lhamilton
  group: mercedes

---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: nrosberg
  namespace: koo-system
spec:
  commonName: Nico ROSBERG
  passwordHash: $2a$10$Jp2kWU1Do71uQkaaOpUHquXgZ.ODSMCRP/7u.hEdD5TW02J5J5EHO  # rosbergn
  email: nico@mercedes.com
  uid: 6
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: nr-williams
  namespace: koo-system
spec:
  user: nrosberg
  group: williams
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: nr-mercedes
  namespace: koo-system
spec:
  user: nrosberg
  group: mercedes

---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: jclark
  namespace: koo-system
spec:
  commonName: Jim CLARK
  passwordHash: $2a$10$wJIUNPjw3pb1UI.opd1FQOqPq7Nn4TyiLOHS/u2Hy93zpAaPG./oq  # clarkj
  email: jimc@lotus.com
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: jc-lotus
  namespace: koo-system
spec:
  user: jclarck
  group: lotus

---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: ghill
  namespace: koo-system
spec:
  commonName: Graham HILL
  # passwordHash: $2a$10$wJIUNPjw3pb1UI.opd1FQOqPq7Nn4TyiLOHS/u2Hy93zpAaPG./oq  # clarkj
  email: grahamh@brm.com
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: gh-lotus
  namespace: koo-system
spec:
  user: ghill
  group: lotus
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: gh-brm
  namespace: koo-system
spec:
  user: ghill
  group: brm
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: gh-brabham
  namespace: koo-system
spec:
  user: ghill
  group: brabham


---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: mercedes
  namespace: koo-system
spec:
  description: German car manufacturer
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: mclaren
  namespace: koo-system
spec:
  description: McLaren
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: williams
  namespace: koo-system
spec:
  description: Team from Franck Williams
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: redbull
  namespace: koo-system
spec:
  description: Soft drink marketer.
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: ferrari
  namespace: koo-system
spec:
  description: Everybody knows
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: renault
  namespace: koo-system
spec:
  description: French car manufacturer
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: lotus
  namespace: koo-system
spec:
  description: Now gone F1 team
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: brm
  namespace: koo-system
spec:
  description: Now gone F1 team
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: brabham
  namespace: koo-system
spec:
  description: Now gone F1 team
