---
apiVersion: v1
kind: Namespace
metadata:
  name: koo-directory
  labels:
    name: koo-directory
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koo-editor-kooadmin
  namespace: koo-directory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kooadmin


---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: gh-lola
  namespace: koo-directory
spec:
  user: ghill
  group: lola
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: lola
  namespace: koo-directory
spec:
  description: British racing car manufacturer




---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: svettel
  namespace: koo-directory
spec:
  commonName: Sebastian Vettel
  passwordHash: $2a$10$3uW8MFgive0RtQDpQoA4sub0r3eNx6EQh2PYyLr3ThxcaQv4Lbz.K  # vettels
  email: seb@ferrari.com
  uid: 5
  disabled: yes
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: sv-redbull
  namespace: koo-directory
spec:
  user: svettel
  group: redbull
  disabled: no
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: redbull
  namespace: koo-directory
spec:
  description: Austrian softdrink maker
  disabled: no

