# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: koocli
before:
  hooks:
    - cd koocli && go mod download && go generate ./...
builds:
- id: koocli
  binary: koocli
  dir: koocli
  env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
release:
  prerelease: true
  extra_files:
    - glob: koomgr/yaml/crd.yaml
    - glob: koomgr/yaml/rbac.yaml
    - glob: koomgr/yaml/pod/deploy.yaml
    - glob: sample/configs/mgrconfig-basic.yaml

archives:
- files:
    - LICENSE
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
