include Makefile.conf

# You can switch between simple (faster) docker build or multiplatform one.
# For multiplatform build on a fresh system, do 'make docker-set-multiplatform-builder'
#DOCKER_BUILD := docker buildx build --builder multiplatform --cache-to type=local,dest=$(BUILDX_CACHE),mode=max --cache-from type=local,src=$(BUILDX_CACHE) --platform linux/amd64,linux/arm64
DOCKER_BUILD := docker build

# Comment this to just build locally
DOCKER_PUSH := --push


.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

.PHONY: version
version: ## Set version in code
	@echo -e "// Generated by Makefile\n\npackage misc\n\nvar version = \"v$(VERSION)\"\n" >koocli/cmd/misc/version_.go
	@echo -e "// Generated by Makefile\n\npackage config\n\nvar Version = \"v$(VERSION)\"\n" >koomgr/internal/config/version_.go

.PHONY: docker
docker: version ## Build and push koo-manager image
	$(DOCKER_BUILD) $(DOCKER_PUSH) -t $(DOCKER_IMG):$(DOCKER_TAG) -f Dockerfile .

doc: ## Generate doc index
	doctoc README.md --github --title '## Index'

