---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "koomgr.certprefix" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "koomgr.service" . }}.{{ .Release.Namespace }}.svc
    - {{ include "koomgr.service" . }}.{{ .Release.Namespace }}.cluster.local
  secretName: {{ include "koomgr.certprefix" . }}-webhook
  issuerRef:
  {{ if .Values.webhooks.certificateClusterIssuer}}
    kind: ClusterIssuer
    name: {{ .Values.webhooks.certificateClusterIssuer }}
  {{ else }}
    kind: Issuer
    name: {{ include "koomgr.selfsigned" . }}
  {{ end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "koomgr.certprefix" . }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.auth.host }}
  secretName: {{ include "koomgr.certprefix" . }}-auth
  issuerRef:
  {{ if .Values.auth.certificateClusterIssuer}}
    kind: ClusterIssuer
    name: {{ .Values.auth.certificateClusterIssuer }}
  {{ else }}
    kind: Issuer
    name: {{ include "koomgr.selfsigned" . }}
  {{ end }}


