# Adds namespace to all resources.
namespace: koo-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: koo-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue
resources:
  - ./webhook_manifests.yaml

patchesStrategicMerge:
  - generated/webhooks_patch.yaml
