---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: koobind-manager
spec:
  selector:
    matchLabels:
      control-plane: koobind-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: koobind-manager
    spec:
      containers:
      - name: manager
        command:
        - /manager
        args: ["--namespace", "$(KOO_NAMESPACE)", "--config", "/etc/koo/cfg/config.yml"]
        image: controller:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: config
            mountPath: /etc/koo/cfg
        ports:
          - containerPort: 8443
            name: webhook-server
            protocol: TCP
          - containerPort: 8444
            name: auth-server
            protocol: TCP
        env:
        - name: KOO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: config
          configMap:
            name: mgrconfig
      serviceAccountName: koo-manager
      terminationGracePeriodSeconds: 10
