apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
spec:
  selector:
    matchLabels:
      control-plane: manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: manager
    spec:
      containers:
      - name: manager
        command:
        - /manager
        args: ["--namespace", "$(KOO_NAMESPACE)", "--config", "/etc/koo/cfg/config.yml"]
        image: controller:latest
        volumeMounts:
          - name: config
            mountPath: /etc/koo/cfg
        env:
        - name: KOO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      volumes:
        - name: config
          configMap:
            name: mgrconfig
      serviceAccountName: koo-manager
      terminationGracePeriodSeconds: 10
