
# We hard code a selfsigned CA, as we need this to remain the same between removal/reinstallation of all stuff
# Otherwhise, will need to update client certificated and API server config each time
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: ""
    cert-manager.io/certificate-name: koobind-selfsigned-ca
    cert-manager.io/common-name: koobind-selfsigned-ca
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: Issuer
    cert-manager.io/issuer-name: selfsigned-init-issuer
    cert-manager.io/uri-sans: ""
  name: koobind-selfsigned-ca
  namespace: system
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnVENDQVNhZ0F3SUJBZ0lRYWZKUFVPK0xXWW9rdUpzT0dUYlUyVEFLQmdncWhrak9QUVFEQWpBZ01SNHcKSEFZRFZRUURFeFZyYjI5aWFXNWtMWE5sYkdaemFXZHVaV1F0WTJFd0hoY05Nakl3T0RFME1Ea3pOVE16V2hjTgpNakl4TVRFeU1Ea3pOVE16V2pBZ01SNHdIQVlEVlFRREV4VnJiMjlpYVc1a0xYTmxiR1p6YVdkdVpXUXRZMkV3CldUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUcGltbG9iWnVqTTgzQjhMRnljc3BEMEdzOHo0UEsKYWIvOGdieHhpMVdQbU9MeENXd01VME9VZDJWdnFIN0UxbUdQK1lFemExU2g4eHY3eWNoa285TXRvMEl3UURBTwpCZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVSt0UFk3alBsCkNuZFgzWDZFOCsvd0lyOHAwNTh3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlFczBTQ1pXazRMQmgwQXJmL08KOGYrdktXcjdMQjZxaUpUNHNiQzhBckZUQWlFQWtkMWNTS3RyWE8wd2VJOGNBb1lNSW56U2FtN3B1c0ZYQ1FVNgpxdGVPaTFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnVENDQVNhZ0F3SUJBZ0lRYWZKUFVPK0xXWW9rdUpzT0dUYlUyVEFLQmdncWhrak9QUVFEQWpBZ01SNHcKSEFZRFZRUURFeFZyYjI5aWFXNWtMWE5sYkdaemFXZHVaV1F0WTJFd0hoY05Nakl3T0RFME1Ea3pOVE16V2hjTgpNakl4TVRFeU1Ea3pOVE16V2pBZ01SNHdIQVlEVlFRREV4VnJiMjlpYVc1a0xYTmxiR1p6YVdkdVpXUXRZMkV3CldUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFUcGltbG9iWnVqTTgzQjhMRnljc3BEMEdzOHo0UEsKYWIvOGdieHhpMVdQbU9MeENXd01VME9VZDJWdnFIN0UxbUdQK1lFemExU2g4eHY3eWNoa285TXRvMEl3UURBTwpCZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVSt0UFk3alBsCkNuZFgzWDZFOCsvd0lyOHAwNTh3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUlFczBTQ1pXazRMQmgwQXJmL08KOGYrdktXcjdMQjZxaUpUNHNiQzhBckZUQWlFQWtkMWNTS3RyWE8wd2VJOGNBb1lNSW56U2FtN3B1c0ZYQ1FVNgpxdGVPaTFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1OZHh6ZUZmR1htYUp5cVZZL2dxOWhFeURvVjJleGMzaDA1TG9zaUorbm9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNllwcGFHMmJvelBOd2ZDeGNuTEtROUJyUE0rRHltbS8vSUc4Y1l0Vmo1amk4UWxzREZORApsSGRsYjZoK3hOWmhqL21CTTJ0VW9mTWIrOG5JWktQVExRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
  name: koobind-selfsigned
  namespace: system
spec:
  ca:
    secretName: koo-koobind-selfsigned-ca   # koo- must be added manually


# Initial generatuion has been performed with the following, then cut/paste from kootmp namespace to this file
#
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: kootmp
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: selfsigned-init-issuer
#  namespace: kootmp
#spec:
#  selfSigned: {}
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: koobind-selfsigned-ca
#  namespace: kootmp
#spec:
#  isCA: true
#  commonName: koobind-selfsigned-ca
#  secretName: koobind-selfsigned-ca
#  privateKey:
#    algorithm: ECDSA
#    size: 256
#  issuerRef:
#    name: selfsigned-init-issuer
#    kind: Issuer
#    group: cert-manager.io
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: koobind-selfsigned
#  namespace: kootmp
#spec:
#  ca:
#    secretName: koobind-selfsigned-ca
#
