
# This is a sample users definition and authorization.
# WARNING: List redefinition in another values file will overwrite existing list.
# So, one may copy the values here to extends
# In other words, the upper valuew file will host the full users and groups list.
users:
  - name: admin
    commonName: Administrator
    email:
    passwordHash: $2a$10$rRL5Tfm5YHLv/d/vDu3bDO8eb92LZAkCqr5Try77R04PGhFfKO0rS  # admin
  - name: guest
    disabled: false
    passwordHash: $2a$10$pmBHSa4db5U44ssmVj97gOV1AlPhxd3dmg4r1/Jv/HYWb50vP9keG # guest
#  - name: jules
#    commonName: Jules Testeur
#    email: jt@test.com
#    passwordHash: $2a$10$rRL5Tfm5YHLv/d/vDu3bDO8eb92LZAkCqr5Try77R04PGhFfKO0rS  # admin
#    uid: 1000
#    comment: "A tester"
#    disabled: True

groups:

  # A group can be defined in one entry with all parameters
  - name: kooadmin
    description: Koobind users administrator
    roles:
      - name: koobind-directory-editor
      - name: koobind-token-editor
    users:
      - name: admin

  - name: clusteradmin
    description: Kubernetes cluster full admin
    clusterRoles:
      - name: cluster-admin
    users:
      - name: admin

  - name: guests
    users:
      - name: guest
    disabled: false

