apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/auth-certs
          name: auth-cert
          readOnly: true
      volumes:
      - name: auth-cert
        secret:
          defaultMode: 420
          secretName: auth-server-cert
