apiVersion: v1
kind: Namespace
metadata:
  name: koo-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: koo-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRQzg1SHZHS3Z1d2pEQU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESXdNVEl4TkRFM1doY05NekF3TkRFNE1USXhOREUzV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQmZZMHF2ZWltWTNRRzljSWIKQWZIOVFrcktzZzNEQnBiOVBFTzRvOFE4S28rVGlXQkZka3BMR3BCbkF6NUcycW5SMzh4Ymp3UGVMR3dISGNmcQp4eHpsZm91OXphZVdQNVpZOEY1Qmw0c09NczkxUFNQSUhEd2IxbHloUHF5anVGM01HZkt4WWJLblFoMXB2ejA0ClBtMVNpbE9Ed1NXUURBOTZOM1dySEI2R2ZialoxZ0o0Ykp5Nm9yMVk2KzA3MkU3SFNoWWNtU3JvUGF5cmdaRHoKY1VJOENNMjIxOWJHYWlqeDNaQk9RQXRmbHY0MDZIR2tiTjhTYkt0ajBhTmp5YjNzMUFTTWRxU3lYVVd3cHVJcwpiMXV4ejBBNnlna2c3UHcvcG5qVXp2MW1ERUNHRjJTK1pHaGZPUzRjdlFhOGpMdmNOenZKWi94Q2x3eCswdFN2CjR2TURBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJdzZVQUFsUGovaFVFNXk0NWN3K2dhMXJWbVAKNHVkMFBnSmEwNS8zMFdERnVDUTE2aU93aG5VcjVpTkJ1a3VzUnh0Q2duMHFvUVFaK2dlSlZxcEw5U2VIVUxvUQp1VHhGMUZYYjVXNUVkTWxrcHlRNnZlTzF2S1FIc2w0Uzkrenp5MFp0MkVuMEptOUZZWVRnQlFUZ0x4MmxBQVlmCjFoelpIVXhadXBTZW1tYXloR3NWT213UXB2eGdRaGtvd0Vuem9qaW5YSk9YcjZ0RUlkMHJMNHBabG1HQ0dRTG0KRkIyVFpkZWNJYUM2NGZMTm5vemVlaG1wSTlMNzVqc2s2bHFIRStFTmY5OTh4V0pkcTEyZlpzMmpJRlp1eS8zawpkem5BV2cwaC9nSDk2Q211WHBzblBUMHFaVE5lNU9xYlM4TFZvdVptVlFGS3dWSVY2S1JxSVY4bDJmND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/mutate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: muser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: koo-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRQzg1SHZHS3Z1d2pEQU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESXdNVEl4TkRFM1doY05NekF3TkRFNE1USXhOREUzV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEQmZZMHF2ZWltWTNRRzljSWIKQWZIOVFrcktzZzNEQnBiOVBFTzRvOFE4S28rVGlXQkZka3BMR3BCbkF6NUcycW5SMzh4Ymp3UGVMR3dISGNmcQp4eHpsZm91OXphZVdQNVpZOEY1Qmw0c09NczkxUFNQSUhEd2IxbHloUHF5anVGM01HZkt4WWJLblFoMXB2ejA0ClBtMVNpbE9Ed1NXUURBOTZOM1dySEI2R2ZialoxZ0o0Ykp5Nm9yMVk2KzA3MkU3SFNoWWNtU3JvUGF5cmdaRHoKY1VJOENNMjIxOWJHYWlqeDNaQk9RQXRmbHY0MDZIR2tiTjhTYkt0ajBhTmp5YjNzMUFTTWRxU3lYVVd3cHVJcwpiMXV4ejBBNnlna2c3UHcvcG5qVXp2MW1ERUNHRjJTK1pHaGZPUzRjdlFhOGpMdmNOenZKWi94Q2x3eCswdFN2CjR2TURBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJdzZVQUFsUGovaFVFNXk0NWN3K2dhMXJWbVAKNHVkMFBnSmEwNS8zMFdERnVDUTE2aU93aG5VcjVpTkJ1a3VzUnh0Q2duMHFvUVFaK2dlSlZxcEw5U2VIVUxvUQp1VHhGMUZYYjVXNUVkTWxrcHlRNnZlTzF2S1FIc2w0Uzkrenp5MFp0MkVuMEptOUZZWVRnQlFUZ0x4MmxBQVlmCjFoelpIVXhadXBTZW1tYXloR3NWT213UXB2eGdRaGtvd0Vuem9qaW5YSk9YcjZ0RUlkMHJMNHBabG1HQ0dRTG0KRkIyVFpkZWNJYUM2NGZMTm5vemVlaG1wSTlMNzVqc2s2bHFIRStFTmY5OTh4V0pkcTEyZlpzMmpJRlp1eS8zawpkem5BV2cwaC9nSDk2Q211WHBzblBUMHFaVE5lNU9xYlM4TFZvdVptVlFGS3dWSVY2S1JxSVY4bDJmND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/validate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
