apiVersion: v1
kind: Namespace
metadata:
  name: koo-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: koo-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/mutate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: muser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/mutate-directory-koobind-io-v1alpha1-group
  failurePolicy: Fail
  name: mgroup.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/mutate-directory-koobind-io-v1alpha1-binding
  failurePolicy: Fail
  name: mbinding.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindings
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: koo-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/validate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/validate-directory-koobind-io-v1alpha1-group
  failurePolicy: Fail
  name: vgroup.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRRFI1WktxYUQ1QUx6QU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdIaGNOTWpBd05ESTFNVFV4TXpFMFdoY05NekF3TkRJek1UVXhNekUwV2pCdU1Rc3dDUVlEVlFRR0V3SkcKVWpFT01Bd0dBMVVFQ0F3RlVHRnlhWE14RGpBTUJnTlZCQWNNQlZCaGNtbHpNUll3RkFZRFZRUUtEQTFDVWs5QgpSRk52Wm5SM1lYSmxNUll3RkFZRFZRUUxEQTFKVkNCRVpYQmhjblJ0Wlc1ME1ROHdEUVlEVlFRRERBWnJiMjl0ClozSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFETTROeU8yUWdzcVI2cFZVMnoKVVBVSi9vTG1DRVJoaGxJYkxMUGlIOHUyL2xnQm5MVFlpQlZmL1Q3bm1ZL1RsZDBjSTY0QVh0bDEwbjRoQVAxdQpGcW5NT1lPSFNBSEVncUlxY21qMVluZVJsWnRBeThMN041UEQrYzRyT2NKb0JORkVmcUJZbTFyNGZ0VVJGUVFOCmlzemdpYnRQZXVOMGx3Q1RjeWlvMHBJdkZpdGtwYXZndnFYMnJhSXgvTmFURjNCVE1RRmRkSzEwb3JUSWtVdEEKNyswV1ZMREVVMWY3RDRpRno2N1JqWUFFWWpIYU9GM3VETXkvK2FOZ0Zhamk1WnpBOU9Wb1YwYVJLcmxWTGxOaQpjaXNnYTZ1Y0tleW0zNXNrd1lybC9ySHV4ekNhV1NhaFFXVTBkOVU2aHdxR2tvYkJGeFFBS2lBM3RNaTB0RUV4CnhTR0ZBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIMUF1QzBTcE5lcFhzN0xXcUpsOWJiUzY4N2kKYktXbktWay93ZGpSYVcybjdObnBQaEIzUUVzclYwVEVWa05tMTljdXlJcWt4OVpQVnByY3lpRWxkdmxRYmZqRQpCNWNJSFlUM1ZMSGpaUlozK3V2ajQ3RzB3bWN5aHRUVmhSMUtNNDE3cEtZTmtqZXB5UjNRWHlvNDN0b3R6b3d3CmRjWlFrRHVrbVRUaTJqbzJySVNubDNicU5RZVlxY2toaXlsb3dKM3NoWFJrRmhIMjJqOWJRd01QbTdPbzZMcHoKbHM4ZjBva2pkblBKYis3YmFIMnNDQWd4M1NMSUZURi83VHZGZEVKaG4xWTE2OFZwbDBycW1kRXYxbkxTbXFhSwpQU0JMOXJJa1kzLzBtQ1JJUFBQeE8xcm4xanozaWg4UkxuUmJveXozNGJYMi9MTGU3QUpjK3IrL01YOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: https://koomgr:9443/validate-directory-koobind-io-v1alpha1-binding
  failurePolicy: Fail
  name: vbinding.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindings
