---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    control-plane: koobind-manager
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: system
spec:
  ports:
    - port: 444
      targetPort: 8444
  selector:
    control-plane: koobind-manager
