---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    control-plane: manager
---
apiVersion: v1
kind: Service
metadata:
  name: external-service
  namespace: system
spec:
  type: NodePort
  ports:
    - port: 444
      targetPort: 8444
      protocol: TCP
      nodePort: 31444
  selector:
    control-plane: manager
