apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller:pspfree
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: manager   # koo- prefix added manually
    namespace: system
