---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koomgr.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
data:
  config.yml: |2
    adminGroup: {{ .Values.config.adminGroup }}
    logLevel: {{ .Values.config.logLevel }}
    logMode: {{ .Values.config.logMode }}
    inactivityTimeout: {{ .Values.config.inactivityTimeout }}
    sessionMaxTTL: {{ .Values.config.sessionMaxTTL }}
    webhookServer:
      port: {{ .Values.services.webhooks.targetPort }}
      certDir: "/tmp/cert/webhook-server"
    authServer:
      enabled: {{ .Values.services.auth.enabled }}
      port: {{ .Values.services.auth.targetPort }}
      certDir: "/tmp/cert/auth-server"
    dexServer:
      enabled: {{ .Values.services.dex.enabled }}
      port: {{ .Values.services.dex.targetPort }}
      certDir: "/tmp/cert/dex-server"
    authClients:
      {{- toYaml .Values.config.authClients | nindent 6 }}
    providers:
      {{- toYaml .Values.config.providers | nindent 6 }}
