# permissions for end users to view directory stuff.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "koomgr.roleprefix" . }}-directory-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - users
  - groupbindings
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - users/status
  verbs:
  - get
