# permissions for end users to view tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "koomgr.roleprefix" . }}-token-viewer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens/status
  verbs:
  - get
