---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "koomgr.serviceAccountName" . }}-directory-editor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "koomgr.roleprefix" . }}-directory-editor
subjects:
  - kind: ServiceAccount
    name:  {{ include "koomgr.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "koomgr.serviceAccountName" . }}-token-editor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "koomgr.roleprefix" . }}-token-editor
subjects:
  - kind: ServiceAccount
    name:  {{ include "koomgr.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
