---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "koomgr.service" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "koomgr.selectorLabels" . | nindent 4 }}
  ports:
    - name: auth-server
      port: {{ .Values.services.auth.servicePort }}
      targetPort: {{ .Values.services.auth.targetPort }}
      protocol: TCP
    - name: webhook-server
      port: {{ .Values.services.webhooks.servicePort }}
      targetPort: {{ .Values.services.webhooks.targetPort }}
      protocol: TCP
