# permissions for end users to edit tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-editor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens/status
  verbs:
  - get
