---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "koomgr.certprefix" . }}-webhook
  name: {{ include "koomgr.fullname" . }}-mutating-webhook
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-directory-koobind-io-v1alpha1-group
    failurePolicy: Fail
    name: mgroup.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - groups
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-directory-koobind-io-v1alpha1-groupbinding
    failurePolicy: Fail
    name: mgroupbinding.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - groupbindings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-directory-koobind-io-v1alpha1-user
    failurePolicy: Fail
    name: muser.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - users
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "koomgr.certprefix" . }}-webhook
  name: {{ include "koomgr.fullname" . }}-validating-webhook
  labels:
    {{- include "koomgr.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-directory-koobind-io-v1alpha1-group
    failurePolicy: Fail
    name: vgroup.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - groups
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-directory-koobind-io-v1alpha1-groupbinding
    failurePolicy: Fail
    name: vgroupbinding.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - groupbindings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "koomgr.service" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-directory-koobind-io-v1alpha1-user
    failurePolicy: Fail
    name: vuser.kb.io
    rules:
      - apiGroups:
          - directory.koobind.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - users
    sideEffects: None
