---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: kooadmin
  namespace: koo-system
spec:
  description: Koobind administrator group
---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: admin
  namespace: koo-system
spec:
  commonName: Koo ADMIN
  passwordHash: $2a$10$rRL5Tfm5YHLv/d/vDu3bDO8eb92LZAkCqr5Try77R04PGhFfKO0rS  # admin
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: admin-kooadmin
  namespace: koo-system
spec:
  user: admin
  group: kooadmin
