---
# Create the 'kooadmin' group
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: kooadmin
  namespace: koo-system
spec:
  description: Koobind administrator group
---
# Allow this group to edit ressources in api group directory.koobind.io
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koo-directory-editor-kooadmin
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-directory-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kooadmin
---
# Allow this group to edit ressources in api group tokens.koobind.io
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koo-token-editor-kooadmin
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-token-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kooadmin

---
# Add the user 'admin' to this group
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: admin-kooadmin
  namespace: koo-system
spec:
  user: admin
  group: kooadmin
