---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: oriley
  namespace: koo-system
spec: {}
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: oriley-kooadmin
  namespace: koo-system
spec:
  user: oriley
  group: kooadmin
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: oriley-cluseradmin
  namespace: koo-system
spec:
  user: oriley
  group: clusteradmin




