
logLevel: 0
adminGroup: "kooadmin"
providers:

  - name: ipa1
    type: ldap
    host: ipa1.vgr.broadsoftware.com
    port: 636
    rootCA: /etc/koo/cfg/ipa1-cert.pem
    bindDN: uid=admin,cn=users,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
    bindPW: ipaadmin
    userSearch:
      baseDN: cn=users,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
      emailAttr: mail
      filter: (objectClass=inetOrgPerson)
      loginAttr: uid
      numericalIdAttr: uidNumber
      cnAttr: cn
    groupSearch:
      baseDN: cn=groups,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
      filter: (objectClass=posixgroup)
      linkGroupAttr: member
      linkUserAttr: DN
      nameAttr: cn

  - name: ldap1
    type: ldap
    host: ldap1
    port: 636
    bindDN: cn=Manager,dc=vgr,dc=broadsoftware,dc=com
    bindPW: LdapAdmin
    rootCA: /etc/koo/cfg/ldap1-ca1.crt
    userSearch:
      baseDN: ou=Users,dc=vgr,dc=broadsoftware,dc=com
      filter: (objectClass=inetOrgPerson)
      loginAttr: uid
      emailAttr: mail
      numericalIdAttr: uidNumber
      cnAttr: cn
    groupSearch:
      baseDN: ou=Groups,dc=vgr,dc=broadsoftware,dc=com
      filter: (objectClass=posixgroup)
      nameAttr: cn
      linkGroupAttr: memberUid
      linkUserAttr: uid

  - name: crdsys
    type: crd

