apiVersion: v1
data:
  config.yml: |2+

    logLevel: 0
    adminGroup: "kooadmin"
    providers:
      - name: ipa1
        type: ldap
        host: ipa1.vgr.broadsoftware.com
        port: 636
        rootCA: /etc/koo/cfg/ldap1-ca1.crt
        bindDN: uid=admin,cn=users,cn=accounts,dc=bsa,dc=broadsoftware,dc=com
        bindPW: ipaadmin
        userSearch:
          baseDN: cn=users,cn=accounts,dc=bsa,dc=broadsoftware,dc=com
          emailAttr: mail
          filter: (objectClass=inetOrgPerson)
          loginAttr: uid
          numericalIdAttr: uidNumber
        groupSearch:
          baseDN: cn=groups,cn=accounts,dc=bsa,dc=broadsoftware,dc=com
          filter: (objectClass=posixgroup)
          linkGroupAttr: member
          linkUserAttr: DN
          nameAttr: cn

  ipa1-cert.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDaTCCAlGgAwIBAgIBATANBgkqhkiG9w0BAQsFADAgMR4wHAYDVQQDDBV2Z3Iu
    YnJvYWRzb2Z0d2FyZS5jb20wHhcNMjAwNTE4MTkwMjMyWhcNNDAwNTE4MTkwMjMy
    WjAgMR4wHAYDVQQDDBV2Z3IuYnJvYWRzb2Z0d2FyZS5jb20wggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQCa0l/QYz9qpaC9gezEtVFPhLeBCUnxmX1YX6zp
    zq2N/agQSYWN7frvemtr0dW4UkzcMQyE/nIKVgKmBbI2+hWiYh7mA/5n8SDWfs8l
    Q4E2Ka1mfB6gD2/RKemiGB39jHzbHk7y3Jo4O/28Oc6qZUU0ynnI1WHGzq89Z03b
    gy//xZbeF6wEYlMuyZTRD3LxLog+aXhq3KVgzxCCTv7UtcMmn32+Gh7z+5lb0Ln2
    QTycfvHUqfiHfUcOh2Xj+Ud+dmbjP+oDbyRk8qy5K8mCLTf+khRAbqseqP6+TIdt
    wuBllc6btq2ZVyJakQZStWLLINX+I5MX/9bRra05NfsIL411AgMBAAGjga0wgaow
    HwYDVR0jBBgwFoAU6exV4CoGeT6fXkbopZZ5ZfooPugwDwYDVR0TAQH/BAUwAwEB
    /zAOBgNVHQ8BAf8EBAMCAcYwHQYDVR0OBBYEFOnsVeAqBnk+n15G6KWWeWX6KD7o
    MEcGCCsGAQUFBwEBBDswOTA3BggrBgEFBQcwAYYraHR0cDovL2lwYS1jYS52Z3Iu
    YnJvYWRzb2Z0d2FyZS5jb20vY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAQEAF7pn
    aGabOItOQxSMu0CsCHie97SdWeAyRoEqqD/+qT+ajlGAkjR/XbhfZW/w2t+cMyk1
    LMGF4pQUDSJ9OIXoDpIJVkdcyR2ASAQq05haVxpotLGMLoVIFsgpfzoEOUctN1hf
    QIRxzJhC24AHvmiV7fJLpYnuzbcx79FHXHlj1U7+5F5ClPWpVfREL2N10ur/eln2
    X+XKLSaRGx+bzuGpM/3stZuZ/TcKvKisix+YgHRQJ7ZQQ7eMcmqObo7fI1hab45x
    IEQZYjQ6ih6wzy6rysjZMbwvm+smWNVRVfGD2WDFOFE7oX8cYaHXJLY7pro7/lIS
    j2nA+rrKpkg1F5c0Cw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mgrconfig
  namespace: koo-system
