apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-editor
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - bindings
  - users
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - bindings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-viewer
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - users
  - bindings
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - users/status
  verbs:
  - get
