apiVersion: v1
kind: ServiceAccount
metadata:
  name: koo-manager
  namespace: koo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-directory-editor
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - groupbindings
  - users
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - groupbindings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-directory-viewer
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - users
  - groupbindings
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - users/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-token-editor
  namespace: koo-system
rules:
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-token-viewer
  namespace: koo-system
rules:
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koo-directory-editor-default
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-directory-editor
subjects:
- kind: ServiceAccount
  name: koo-manager
  namespace: koo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koo-token-editor-default
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-token-editor
subjects:
- kind: ServiceAccount
  name: koo-manager
  namespace: koo-system
