apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koo-directory-editor-kooadmin
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-directory-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kooadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: koo-token-editor-kooadmin
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-token-editor
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kooadmin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: clusteradmin
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: clusteradmin
  namespace: koo-system
spec:
  description: Cluster administrator group
---
apiVersion: directory.koobind.io/v1alpha1
kind: Group
metadata:
  name: kooadmin
  namespace: koo-system
spec:
  description: Koobind administrator group
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: admin-clusteradmin
  namespace: koo-system
spec:
  group: clusteradmin
  user: admin
---
apiVersion: directory.koobind.io/v1alpha1
kind: GroupBinding
metadata:
  name: admin-kooadmin
  namespace: koo-system
spec:
  group: kooadmin
  user: admin
---
apiVersion: directory.koobind.io/v1alpha1
kind: User
metadata:
  name: admin
  namespace: koo-system
spec:
  commonName: Koo ADMIN
  passwordHash: $2a$10$rRL5Tfm5YHLv/d/vDu3bDO8eb92LZAkCqr5Try77R04PGhFfKO0rS
