# Adds namespace to all resources.
namespace: koo-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: koo-


resources:
  - directory_editor_role.yaml
  - directory_viewer_role.yaml
  - token_editor_role.yaml
  - token_viewer_role.yaml
  