# permissions for end users to edit tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-editor
rules:
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokens.koobind.io
  resources:
  - tokens/status
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-editor-default
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-editor
subjects:
  - kind: ServiceAccount
    name: manager
    namespace: system
