# permissions for end users to view users.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer-role
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - users
  - bindings
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - users/status
  verbs:
  - get
