

doctoc:
	doctoc installation.md --github --title '**Index**'
	doctoc usage.md --github --title '**Index**'
	doctoc configuration.md --github --title '**Index**'
	doctoc ldap.md --github --title '**Index**'
	doctoc providerchain.md --github --title '**Index**'

