# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/directory.koobind.io_users.yaml
- bases/directory.koobind.io_groups.yaml
- bases/directory.koobind.io_groupbindings.yaml
- bases/tokens.koobind.io_tokens.yaml
# +kubebuilder:scaffold:crdkustomizeresource
