apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
  name: koo-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: koo-system/koo-serving-cert
  creationTimestamp: null
  name: koo-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /mutate-directory-koobind-io-v1alpha1-binding
  failurePolicy: Fail
  name: mbinding.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindings
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /mutate-directory-koobind-io-v1alpha1-group
  failurePolicy: Fail
  name: mgroup.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /mutate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: muser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-editor
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - bindings
  - users
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - bindings/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: koo-viewer
  namespace: koo-system
rules:
- apiGroups:
  - directory.koobind.io
  resources:
  - users
  - bindings
  - groups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - directory.koobind.io
  resources:
  - users/status
  verbs:
  - get
---
apiVersion: v1
kind: Service
metadata:
  name: koo-webhook-service
  namespace: koo-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: manager
  name: koo-manager
  namespace: koo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: manager
  template:
    metadata:
      labels:
        control-plane: manager
    spec:
      containers:
      - args:
        - --namespace
        - $(KOO_NAMESPACE)
        command:
        - /manager
        env:
        - name: KOO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: koobind/manager:latest
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: koo-serving-cert
  namespace: koo-system
spec:
  dnsNames:
  - koo-webhook-service.koo-system.svc
  - koo-webhook-service.koo-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: koo-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: koo-selfsigned-issuer
  namespace: koo-system
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: koo-system/koo-serving-cert
  creationTimestamp: null
  name: koo-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /validate-directory-koobind-io-v1alpha1-binding
  failurePolicy: Fail
  name: vbinding.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bindings
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /validate-directory-koobind-io-v1alpha1-group
  failurePolicy: Fail
  name: vgroup.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groups
- clientConfig:
    caBundle: Cg==
    service:
      name: koo-webhook-service
      namespace: koo-system
      path: /validate-directory-koobind-io-v1alpha1-user
  failurePolicy: Fail
  name: vuser.kb.io
  rules:
  - apiGroups:
    - directory.koobind.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
